<?php
/**
 * Project Euler - Problem 45
 *
 * Triangular, pentagonal, and hexagonal
 *
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 * Triangle   T<sub>n</sub> = n(n+1)/2   1, 3, 6, 10, 15, ...
 * Pentagonal P<sub>n</sub> = n(3n−1)/2  1, 5, 12, 22, 35, ...
 * Hexagonal  H<sub>n</sub> = n(2n−1)    1, 6, 15, 28, 45, ...
 * 
 * It can be verified that T of 285 = P of 165 = H of 143 = 40755.
 * Find the next triangle number that is also pentagonal and hexagonal. 
 *
 * @category ProjectEuler
 * @package Problem45
 * @author Michael Reeves <mike.reeves@gmail.com>
 * @link http://projecteuler.net/problem=45
 *
 */
class Problem45 extends Problem_Abstract
{
    /**
     * Project Euler says each problem should take no more than 1 minute. 
     * If your computer is slow make this larger.
     * @const int TIMEOUT_OVERRIDE Used with an override method to control how long it 
     * takes for the script to timeout
     */
    const TIMEOUT_OVERRIDE = 60;

    /**
     * Project Euler is silent on space complexity. PHP uses a LOT of memory for arrays. 
     * Something like 20x what you would expect. 
     * @const int MEMORY_OVERRIDE Used with an override method to control how much memory
     * the script is allowed to consume.
     */
    const MEMORY_OVERRIDE = '64M';

    /**
     * Description of input
     * @const string INPUT
     */
    const INPUT = '';

    /**
     * Override default timeout of 60 seconds
     */
    public function __construct()
    {
        parent::__construct(); 

        // $this->overrideTimeoutAndMemoryLimit(self::TIMEOUT_OVERRIDE, self::MEMORY_OVERRIDE);

        if (!extension_loaded('bcmath')) {
            // Placeholder for any extensions required for this problem's code
            // die('BCMath extension required. See http://www.php.net/manual/en/book.bc.php .');
        }
    }

    /**
     * Wrapper method to output our answer with the appropriate input variables
     *
     * @return int
     */
    public function execute()
    {
        return $this->findSomething(self::INPUT);
    }

    /**
     * Find "Something".
     *
     * @param string $number description
     *
     * @return int description
     */
    private function findSomething($number){

        return;
    }
}
